# Generated by Django 5.2.6 on 2025-09-16 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], default='Product', max_length=100),
        ),
    ]
